src/authentication/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'auth'

urlpatterns = [
    path(_('login/'), views.SVLoginView.as_view(), name='login'),
    path(_('logout/'), views.SVLogoutView.as_view(), name='logout'),
    path(_('password-change/'), views.SVPasswordChangeView.as_view(), name='password-change'),
    path(_('password-reset/'), views.SVPasswordResetView.as_view(), name='password-reset'),
    path(_('password-reset-confirm/<uidb64>/<token>/'), views.SVPasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path(_('register/'), views.UserRegistrationView.as_view(), name='register'),
    path(_('register-confirm/<uidb64>/<token>/'), views.UserRegistrationConfirmView.as_view(),
         name='register-confirm'),
    path(_('administration/'), views.AdministrationView.as_view(), name='administration'),
    path(_('delete-rr/<pk>/'), views.RegistrationRequestDeleteView.as_view(), name='delete_rr'),
    path(_('confirm-rr/<pk>/'), views.RegistrationRequestConfirmView.as_view(), name='confirm_rr'),
    path(_('settings/'), views.SettingsListView.as_view(), name='settings'),
    path(
        _('create-bankdetails/'),
        views.BankDetailsCreateView.as_view(),
        name='create_bankdetails'
    ),
    path(
        _('edit-bankdetails/<pk>/'),
        views.BankDetailsUpdateView.as_view(),
        name='edit_bankdetails'
    ),
    path(
        _('delete-bankdetails/<pk>/'),
        views.BankDetailsDeleteView.as_view(),
        name='delete_bankdetails'
    ),
    path(
        _('edit-user/<pk>/'),
        views.SVUserUpdateView.as_view(),
        name='edit_user'
    ),
    path(
        _('delete-user/<pk>/'),
        views.SVUserDeleteView.as_view(),
        name='delete_user'
    ),
    path(_('legal-terms/'), views.LegalTermsView.as_view(), name='legal_terms'),
    path(_('privacy-policy/'), views.PrivacyPolicyView.as_view(), name='privacy_policy'),
]

src/events/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'events'

urlpatterns = [
    path(
        _('subvention-list/<event>/'),
        views.SubventionListView.as_view(),
        name='subvention_list'
    ),
    path(
        _('participant-list/<event>/'),
        views.ParticipantListView.as_view(),
        name='participant_list'
    ),
    path(_('create-event/'), views.EventCreateWizardView.as_view(), name='create_event'),
    path(_('edit-event/<pk>/'), views.EventUpdateView.as_view(), name='edit_event'),
    path(_('delete-event/<pk>/'), views.EventDeleteView.as_view(), name='delete_event'),
    path(
        _('create-participation/<event>/'),
        views.ParticipationCreateView.as_view(),
        name='create_participation'
    ),
    path(
        _('edit-participation/<pk>/'),
        views.ParticipationUpdateView.as_view(),
        name='edit_participation'
    ),
    path(
        _('delete-participation/<pk>/'),
        views.ParticipationDeleteView.as_view(),
        name='delete_participation'
    ),
    path(_('letter-preview/'), views.LetterPreviewView.as_view(), name='letter_preview'),
    path('<pk>/', views.EventDetailView.as_view(), name='details'),
    path('', views.EventListView.as_view(), name='list'),
]

src/finances/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'finances'

urlpatterns = [
    path(
        _('debits/'),
        views.DebitListView.as_view(),
        name='debits'
    ),
    path(
        _('settlements/'),
        views.SettlementListView.as_view(),
        name='settlements'
    ),
    path(
        _('donations/<year>/'),
        views.DonationListView.as_view(),
        name='donations'
    ),
    path(
        _('entries/<year>/'),
        views.EntryListView.as_view(),
        name='entries'
    ),
    path(
        _('edit-entry/<pk>/'),
        views.EntryUpdateView.as_view(),
        name='edit_entry'
    ),
    path(
        _('delete-entry/<pk>/'),
        views.EntryDeleteView.as_view(),
        name='delete_entry'
    ),
    path(
        _('accounts/<year>/'),
        views.AccountListView.as_view(),
        name='accounts'
    ),
    path(_('old-debits/<group>/'), views.OldDebitListView.as_view(), name='old_debits'),
    path(_('create-debit/'), views.DebitCreateView.as_view(), name='create_debit'),
    path(_('edit-debit/<pk>/'), views.DebitUpdateView.as_view(), name='edit_debit'),
    path(_('delete-debit/<pk>/'), views.DebitDeleteView.as_view(), name='delete_debit'),
    path(_('export-debits/<group>/'), views.DebitsExportView.as_view(), name='export_debits'),
    path(
        _('create-mfc/'),
        views.MembershipFeeCollectionCreateView.as_view(),
        name='create_mfc'
    ),
    path(
        _('create-event-debits/<event>/'),
        views.EventDebitCreateView.as_view(),
        name='create_event_debits'
    ),
    path(
        _('create-entry/'),
        views.EntryCreateView.as_view(),
        name='create_entry'
    ),
    path(
        _('create-account/'),
        views.AccountCreateView.as_view(),
        name='create_account'
    ),
    path(
        _('create-contra-account/'),
        views.ContraAccountCreateView.as_view(),
        name='create_contra_account'
    ),
    path(
        _('edit-account/<pk>/'),
        views.AccountUpdateView.as_view(),
        name='edit_account'
    ),
    path(
        _('close-accounts/<year>/'),
        views.AccountCloseView.as_view(),
        name='close_accounts'
    ),
    path(
        _('export-entry/<year>/'),
        views.EntryExportView.as_view(),
        name='export_entry'
    ),
    path(
        _('export-voucher/<year>/'),
        views.VoucherExportView.as_view(),
        name='export_voucher'
    ),
    path(
        _('event-export-voucher/<event>/'),
        views.EventVoucherExportView.as_view(),
        name='event_export_voucher'
    ),
    path(
        _('export-account/<year>/'),
        views.AccountExportView.as_view(),
        name='export_account'
    ),
    path(
        _('create-settlement/'),
        views.SettlementCreateView.as_view(),
        name='create_settlement'
    ),
    path(
        _('edit-settlement/<pk>/'),
        views.SettlementUpdateView.as_view(),
        name='edit_settlement'
    ),
    path(
        _('delete-settlement/<pk>/'),
        views.SettlementDeleteView.as_view(),
        name='delete_settlement'
    ),
    path(
        _('book-settlement/<pk>/'),
        views.SettlementBookView.as_view(),
        name='book_settlement'
    ),
    path(
        _('create-event-account/<event>/'),
        views.EventAccountCreateView.as_view(),
        name='create_event_account'
    ),
    path(
        _('create-donation/'),
        views.DonationCreateView.as_view(),
        name='create_donation'
    ),
    path(
        _('edit-donation/<pk>/'),
        views.DonationUpdateView.as_view(),
        name='edit_donation'
    ),
    path(
        _('delete-donation/<pk>/'),
        views.DonationDeleteView.as_view(),
        name='delete_donation'
    ),
    path(
        _('create-travelingcost/'),
        views.TravelingCostCreateView.as_view(),
        name='create_travelingcost'
    ),
    path(
        _('edit-travelingcost/<pk>/'),
        views.TravelingCostUpdateView.as_view(),
        name='edit_travelingcost'
    ),
    path(
        _('delete-travelingcost/<pk>/'),
        views.TravelingCostDeleteView.as_view(),
        name='delete_travelingcost'
    ),
    path(
        _('export-donations/<year>/'),
        views.DonationExportView.as_view(),
        name='export_donations'
    ),
]

src/members/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'members'

urlpatterns = [
    path(_('create-member/'), views.MemberCreateView.as_view(), name='create_member'),
    path(_('edit-member/<pk>/'), views.MemberUpdateView.as_view(), name='edit_member'),
    path(_('delete-member/<pk>/'), views.MemberDeleteView.as_view(), name='delete_member'),
    path(_('create-mandate/'), views.MandateCreateView.as_view(), name='create_mandate'),
    path(_('edit-mandate/<pk>/'), views.MandateUpdateView.as_view(), name='edit_mandate'),
    path(_('delete-mandate/<pk>/'), views.MandateDeleteView.as_view(), name='delete_mandate'),
    path(_('mfc/'), views.MembershipFeeCollectionListView.as_view(), name='mfc'),
    path(_('list-members/'), views.MemberListView.as_view(), name='list_member'),
    path(_('list-mandates/'), views.MandateListView.as_view(), name='list_mandate'),
    path(_('member/<pk>/'), views.MemberDetailView.as_view(), name='details_member'),
    path(_('export-members/'), views.MemberExportView.as_view(), name='export_members'),
    path(_('create-section/'), views.SectionCreateView.as_view(), name='create_section'),
    path(_('edit-section/<pk>/'), views.SectionUpdateView.as_view(), name='edit_section'),
    path(_('delete-section/<pk>/'), views.SectionDeleteView.as_view(), name='delete_section'),
]

src/stock/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'stock'

urlpatterns = [
    path(
        _('orders/'),
        views.OrderListView.as_view(),
        name='orders'
    ),
    path(
        _('create-order/'),
        views.OrderCreateView.as_view(),
        name='create_order'
    ),
    path(
        _('edit-order/<pk>/'),
        views.OrderUpdateView.as_view(),
        name='edit_order'
    ),
    path(
        _('delete-order/<pk>/'),
        views.OrderDeleteView.as_view(),
        name='delete_order'
    ),
    path(
        _('complete-order/<pk>/'),
        views.OrderCompleteView.as_view(),
        name='complete_order'
    ),
    path(
        _('stock/'),
        views.StockListView.as_view(),
        name='stock'
    ),
    path(
        _('create-stock/'),
        views.StockCreateView.as_view(),
        name='create_stock'
    ),
    path(
        _('edit-stock/<pk>/'),
        views.StockUpdateView.as_view(),
        name='edit_stock'
    ),
    path(
        _('delete-stock/<pk>/'),
        views.StockDeleteView.as_view(),
        name='delete_stock'
    ),
    path(
        _('reservations/<stock>/'),
        views.ReservationListView.as_view(),
        name='reservations'
    ),
    path(
        _('create-reservation/<stock>/'),
        views.ReservationCreateView.as_view(),
        name='create_reservation'
    ),
    path(
        _('edit-reservation/<pk>/'),
        views.ReservationUpdateView.as_view(),
        name='edit_reservation'
    ),
    path(
        _('delete-reservation/<pk>/'),
        views.ReservationDeleteView.as_view(),
        name='delete_reservation'
    ),
]

src/templates/_base.html
{% load i18n %}
{% load static %}
{% load permission_tags %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		{% block title %}
			<title>
				{% trans "Stammesverwaltung" %}
			</title>
		{% endblock %}

		{% block css %}
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
			<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
			<link rel="shortcut icon" type="image/png" href="{% static "img/favicon.png" %}"/>
			{{ form.media.css }}
		{% endblock %}

		{% block js %}
			<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
			<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
			<script src="{% static "js/jquery.formset.js" %}"></script>
			{{ form.media.js }}
		{% endblock %}
	</head>
	<body>
		{% block navbar %}
			{% if not view.is_popup %}
				<nav class="navbar sticky-top navbar-expand-lg navbar-light">
					<a class="navbar-brand py-0" href="/">
						<img src="{% static "img/logo.png" %}" height="50">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					
					<div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
						<div class="navbar-nav mr-auto">
							<div class="nav-item">
								<a class="nav-link btn btn-dark btn-nav my-1 mx-2 px-3" href="{% url 'events:list' %}">{% trans "Events" %}</a>
							</div>
							<div class="nav-item dropdown active">
								<a class="nav-link btn btn-dark btn-nav dropdown-toggle my-2 my-sm-1 mx-2 px-3" href="/" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Members" %}</a>
								<div class="dropdown-menu mx-2">
									<a class="dropdown-item" href="{% url "members:list_member" %}">{% trans "Members" %}</a>
									<a class="dropdown-item" href="{% url "members:list_mandate" %}">{% trans "SEPA mandates" %}</a>
									{% if user|has_role:'board,cashier,secretary,leader' %}
										<a class="dropdown-item" href="{% url "members:mfc" %}">{% trans "Membership fee collections" %}</a>
									{% endif %}
								</div>
							</div>
							{% if user|has_role:'board,cashier,leader' %}
								<div class="nav-item dropdown active">
									<a class="nav-link btn btn-dark btn-nav dropdown-toggle my-2 my-sm-1 mx-2 px-3" href="/" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Finances" %}</a>
									<div class="dropdown-menu mx-2">
										<a class="dropdown-item" href="{% url "finances:debits" %}">{% trans "Debits" %}</a>
										<a class="dropdown-item" href="{% url "finances:settlements" %}">{% trans "Settlements" %}</a>
										<a class="dropdown-item" href="{% now "Y" as year %}{% url "finances:donations" year %}">{% trans "Donation receipt" %}</a>
										<a class="dropdown-item" href="{% now "Y" as year %}{% url "finances:entries" year %}">{% trans "Entries" %}</a>
										<a class="dropdown-item" href="{% now "Y" as year %}{% url "finances:accounts" year %}">{% trans "Accounts" %}</a>
									</div>
								</div>
							{% else %}
								<div class="nav-item">
									<a class="nav-link btn btn-dark btn-nav my-1 mx-2 px-3" href="{% url 'finances:debits' %}">{% trans "Debits" %}</a>
								</div>
							{% endif %}
							{% if user|has_role:'board,leader,stock_warden' %}
								<div class="nav-item dropdown active">
									<a class="nav-link btn btn-dark btn-nav dropdown-toggle my-2 my-sm-1 mx-2 px-3" href="/" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Stock" %}</a>
									<div class="dropdown-menu mx-2">
										<a class="dropdown-item" href="{% url "stock:stock" %}">{% trans "Stock list" %}</a>
										<a class="dropdown-item" href="{% url "stock:orders" %}">{% trans "Orders" %}</a>
									</div>
								</div>
							{% else %}
								<div class="nav-item">
									<a class="nav-link btn btn-dark btn-nav my-1 mx-2 px-3" href="{% url 'stock:orders' %}">{% trans "Orders" %}</a>
								</div>
							{% endif %}
							<div class="nav-item">
								<a class="nav-link btn btn-dark btn-nav my-1 mx-2 px-3" target="_blank" href="https://dschraudner.gitlab.io/stammesverwaltung_doc/">{% trans "Help" %}</a>
							</div>
						</div>
						<div class="navbar-nav">
							<div class="nav-item dropdown active">
								<a class="nav-link btn btn-dark btn-nav dropdown-toggle my-2 my-sm-1 mx-2 px-3" href="/" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.get_full_name }}</a>
								<div class="dropdown-menu mx-2">
									{% if user|has_role:'board' %}
										<a class="dropdown-item" href="{% url "auth:administration" %}">{% trans "Administration" %}</a>
									{% endif %}
									<a class="dropdown-item" href="{% url "auth:settings" %}">{% trans "Settings" %}</a>
									<a class="dropdown-item" href="{% url "auth:password-change" %}">{% trans "Change password" %}</a>
									<a class="dropdown-item" href="{% url "auth:logout" %}">{% trans "Logout" %}</a>
								</div>
							</div>
						</div>
					</div>
				</nav>
			{% endif %}
		{% endblock %}

		<div class="container-fluid pt-sm-5 px-sm-5 pt-3 pb-5 px-3">
			{% block messages %}
				{% for message in messages %}
					<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
						{{ message }}
					</div>
				{% endfor %}
			{% endblock %}

			{% block content %}
				<div class="row">
					<div class="col-sm mx-2 jumbotron">
						One
					</div>
					<div class="col-sm mx-2 jumbotron">
						Two
					</div>
				</div>
			{% endblock %}
		</div>
		{% block footer %}
			{% if not view.is_popup %}
				<footer class="footer">
					<div class="container text-center py-3">
						© {% now "Y" %}:
						<a href="https://pfadfinder-hirschaid.de/">DPSG St. Vitus Hirschaid</a> |
						<a href="{% url "auth:legal_terms" %}">{% trans "Legal Terms" %}</a> |
						<a href="{% url "auth:privacy_policy" %}">{% trans "Privacy Policy" %}</a>
					</div>
				</footer>
			{% endif %}
		{% endblock %}
	</body>
</html>