src/finances/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'finances'

urlpatterns = [
    path(
        _('debits/'),
        views.DebitListView.as_view(),
        name='debits'
    ),
    path(
        _('settlements/'),
        views.SettlementListView.as_view(),
        name='settlements'
    ),
    path(
        _('donations/<year>/'),
        views.DonationListView.as_view(),
        name='donations'
    ),
    path(
        _('entries/<year>/'),
        views.EntryListView.as_view(),
        name='entries'
    ),
    path(
        _('edit-entry/<pk>/'),
        views.EntryUpdateView.as_view(),
        name='edit_entry'
    ),
    path(
        _('delete-entry/<pk>/'),
        views.EntryDeleteView.as_view(),
        name='delete_entry'
    ),
    path(
        _('accounts/<year>/'),
        views.AccountListView.as_view(),
        name='accounts'
    ),
    path(_('old-debits/<group>/'), views.OldDebitListView.as_view(), name='old_debits'),
    path(_('create-debit/'), views.DebitCreateView.as_view(), name='create_debit'),
    path(_('edit-debit/<pk>/'), views.DebitUpdateView.as_view(), name='edit_debit'),
    path(_('delete-debit/<pk>/'), views.DebitDeleteView.as_view(), name='delete_debit'),
    path(_('export-debits/<group>/'), views.DebitsExportView.as_view(), name='export_debits'),
    path(
        _('create-mfc/'),
        views.MembershipFeeCollectionCreateView.as_view(),
        name='create_mfc'
    ),
    path(
        _('create-event-debits/<event>/'),
        views.EventDebitCreateView.as_view(),
        name='create_event_debits'
    ),
    path(
        _('create-entry/'),
        views.EntryCreateView.as_view(),
        name='create_entry'
    ),
    path(
        _('create-account/'),
        views.AccountCreateView.as_view(),
        name='create_account'
    ),
    path(
        _('create-contra-account/'),
        views.ContraAccountCreateView.as_view(),
        name='create_contra_account'
    ),
    path(
        _('edit-account/<pk>/'),
        views.AccountUpdateView.as_view(),
        name='edit_account'
    ),
    path(
        _('close-accounts/<year>/'),
        views.AccountCloseView.as_view(),
        name='close_accounts'
    ),
    path(
        _('export-entry/<year>/'),
        views.EntryExportView.as_view(),
        name='export_entry'
    ),
    path(
        _('export-voucher/<year>/'),
        views.VoucherExportView.as_view(),
        name='export_voucher'
    ),
    path(
        _('event-export-voucher/<event>/'),
        views.EventVoucherExportView.as_view(),
        name='event_export_voucher'
    ),
    path(
        _('export-account/<year>/'),
        views.AccountExportView.as_view(),
        name='export_account'
    ),
    path(
        _('create-settlement/'),
        views.SettlementCreateView.as_view(),
        name='create_settlement'
    ),
    path(
        _('edit-settlement/<pk>/'),
        views.SettlementUpdateView.as_view(),
        name='edit_settlement'
    ),
    path(
        _('delete-settlement/<pk>/'),
        views.SettlementDeleteView.as_view(),
        name='delete_settlement'
    ),
    path(
        _('book-settlement/<pk>/'),
        views.SettlementBookView.as_view(),
        name='book_settlement'
    ),
    path(
        _('create-event-account/<event>/'),
        views.EventAccountCreateView.as_view(),
        name='create_event_account'
    ),
    path(
        _('create-donation/'),
        views.DonationCreateView.as_view(),
        name='create_donation'
    ),
    path(
        _('edit-donation/<pk>/'),
        views.DonationUpdateView.as_view(),
        name='edit_donation'
    ),
    path(
        _('delete-donation/<pk>/'),
        views.DonationDeleteView.as_view(),
        name='delete_donation'
    ),
    path(
        _('create-travelingcost/'),
        views.TravelingCostCreateView.as_view(),
        name='create_travelingcost'
    ),
    path(
        _('edit-travelingcost/<pk>/'),
        views.TravelingCostUpdateView.as_view(),
        name='edit_travelingcost'
    ),
    path(
        _('delete-travelingcost/<pk>/'),
        views.TravelingCostDeleteView.as_view(),
        name='delete_travelingcost'
    ),
    path(
        _('export-donations/<year>/'),
        views.DonationExportView.as_view(),
        name='export_donations'
    ),
]

src/stock/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'stock'

urlpatterns = [
    path(
        _('orders/'),
        views.OrderListView.as_view(),
        name='orders'
    ),
    path(
        _('create-order/'),
        views.OrderCreateView.as_view(),
        name='create_order'
    ),
    path(
        _('edit-order/<pk>/'),
        views.OrderUpdateView.as_view(),
        name='edit_order'
    ),
    path(
        _('delete-order/<pk>/'),
        views.OrderDeleteView.as_view(),
        name='delete_order'
    ),
    path(
        _('complete-order/<pk>/'),
        views.OrderCompleteView.as_view(),
        name='complete_order'
    ),
    path(
        _('stock/'),
        views.StockListView.as_view(),
        name='stock'
    ),
    path(
        _('create-stock/'),
        views.StockCreateView.as_view(),
        name='create_stock'
    ),
    path(
        _('edit-stock/<pk>/'),
        views.StockUpdateView.as_view(),
        name='edit_stock'
    ),
    path(
        _('delete-stock/<pk>/'),
        views.StockDeleteView.as_view(),
        name='delete_stock'
    ),
    path(
        _('reservations/<stock>/'),
        views.ReservationListView.as_view(),
        name='reservations'
    ),
    path(
        _('create-reservation/<stock>/'),
        views.ReservationCreateView.as_view(),
        name='create_reservation'
    ),
    path(
        _('edit-reservation/<pk>/'),
        views.ReservationUpdateView.as_view(),
        name='edit_reservation'
    ),
    path(
        _('delete-reservation/<pk>/'),
        views.ReservationDeleteView.as_view(),
        name='delete_reservation'
    ),
]

src/finances/models.py
from django.db import models
from django.db.models import Count, Sum
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from decimal import Decimal

from members.models import Member
from authentication.models import BankDetails
from events.models import Participation

# Create your models here.

ACCOUNT_TYPES = (
    (0, _('Asset account')),
    (1, _('Profit and loss account')),
)


class MembershipFeeCollection(models.Model):
    year = models.IntegerField(_('Year'))
    nr = models.IntegerField(_('Nr.'))

    def __str__(self):
        return '%s/%s' % (self.year, self.nr)

    def reference(self):
        if self.debit_set.exists():
            return self.debit_set.first().reference

    reference.short_description = _('Reference')

    def count(self):
        return self.debit_set.aggregate(Count('id'))['id__count']

    count.short_description = _('Count')

    def sum(self):
        return self.debit_set.aggregate(Sum('amount'))['amount__sum']

    sum.short_description = _('Sum')

    class Meta:
        verbose_name = _('Membership fee collection')
        verbose_name_plural = _('Membership fee collections')
        ordering = ['year', 'nr']


class DebitGroup(models.Model):
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))
    execution_date = models.DateField(_('execution date'))
    notified = models.BooleanField(_('notified'), default=False)

    def __str__(self):
        return str(self.execution_date)

    def count(self):
        return self.debit_set.aggregate(Count('id'))['id__count']

    count.short_description = _('Count')

    def sum(self):
        return self.debit_set.aggregate(Sum('amount'))['amount__sum'] or Decimal('0')

    sum.short_description = _('Sum')

    class Meta:
        verbose_name = _('Debit group')
        verbose_name_plural = _('Debit groups')
        ordering = ['-to_date']


class Debit(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_('member'))
    amount = models.DecimalField(_('amount'), max_digits=5, decimal_places=2)
    reference = models.CharField(_('reference'), max_length=100)
    group = models.ForeignKey(DebitGroup, on_delete=models.PROTECT, verbose_name=_('group'))
    mfc = models.ForeignKey(
        MembershipFeeCollection,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    participation = models.ForeignKey(
        Participation,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def __str__(self):
        return '%s (%s)' % (self.reference, self.member)

    def mandate(self):
        if self.mfc is not None:
            return self.member.mandate_membership_fee
        else:
            return self.member.mandate_participation_fee

    mandate.short_description = _('Mandate')

    class Meta:
        verbose_name = _('debit')
        verbose_name_plural = _('debits')
        ordering = ['member', 'reference']


class Account(models.Model):
    name = models.CharField(_('name'), max_length=50)
    type = models.IntegerField(_('type'), choices=ACCOUNT_TYPES)
    year = models.IntegerField(_('year'))
    closed = models.BooleanField(_('closed'), default=False)

    def __str__(self):
        return '%s %s' % (self.name, self.year)

    @cached_property
    def get_entries_with_type(self):
        result = list()
        debits = self.debit.all().select_related(
            'debit_account',
            'credit_account'
        )
        for debit in debits:
            result.append(('debit', debit))
        credits = self.credit.all().select_related(
            'debit_account',
            'credit_account'
        )
        for credit in credits:
            result.append(('credit', credit))
        return result

    @cached_property
    def get_balance_with_type(self):
        debit_sum = 0
        debits = self.debit.all()
        for debit in debits:
            debit_sum = debit_sum + debit.amount
        credit_sum = 0
        credits = self.credit.all()
        for credit in credits:
            credit_sum = credit_sum + credit.amount
        if debit_sum > credit_sum:
            return ('debit', debit_sum - credit_sum)
        else:
            return ('credit', credit_sum - debit_sum)

    class Meta:
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')
        ordering = ['year', 'type', 'name']


class Entry(models.Model):
    date = models.DateField(_('date'))
    amount = models.DecimalField(_('amount'), max_digits=7, decimal_places=2)
    voucher = models.FileField(_('voucher'), null=True, blank=True)
    comment = models.CharField(_('comment'), max_length=100)
    debit_account = models.ForeignKey(
        Account,
        verbose_name=_('debit account'),
        on_delete=models.PROTECT,
        related_name='debit'
    )
    credit_account = models.ForeignKey(
        Account,
        verbose_name=_('credit account'),
        on_delete=models.PROTECT,
        related_name='credit'
    )

    def __str__(self):
        return '%s -> %s: %s (%s)' % (
            self.debit_account,
            self.credit_account,
            self.amount,
            self.comment
        )

    class Meta:
        verbose_name = _('Entry')
        verbose_name_plural = _('Entries')
        ordering = ['date', 'id']


class Settlement(models.Model):
    amount = models.DecimalField(_('amount'), max_digits=7, decimal_places=2)
    voucher = models.FileField(_('voucher'))
    comment = models.CharField(_('comment'), max_length=100)
    contra_account = models.ForeignKey(
        Account,
        verbose_name=_('contra account'),
        on_delete=models.PROTECT
    )
    payee = models.ForeignKey(
        BankDetails,
        verbose_name=_('payee'),
        on_delete=models.PROTECT
    )
    entry = models.ForeignKey(
        Entry,
        verbose_name=_('entry'),
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )

    def __str__(self):
        return '%s: %s (%s)' % (
            self.comment,
            self.amount,
            self.payee
        )

    class Meta:
        verbose_name = _('Settlement')
        verbose_name_plural = _('Settlements')
        ordering = ['payee', 'id']


class Donation(models.Model):
    date = models.DateField(_('date'))
    name = models.CharField(_('name'), max_length=100)
    amount = models.DecimalField(_('amount'), max_digits=7, decimal_places=2)
    comment = models.CharField(_('comment'), max_length=100)
    payee = models.ForeignKey(
        Member,
        verbose_name=_('payee'),
        on_delete=models.CASCADE
    )

    def __str__(self):
        return '%s (%s)' % (
            self.name,
            self.payee
        )

    class Meta:
        verbose_name = _('Donation')
        verbose_name_plural = _('Donation')
        ordering = ['date', 'payee', 'id']


class TravelingCost(models.Model):
    date = models.DateField(_('date'))
    kilometers = models.IntegerField(_('kilometers'))
    from_place = models.CharField(_('from'), max_length=50)
    to_place = models.CharField(_('to'), max_length=50)
    comment = models.CharField(_('comment'), max_length=100)
    payee = models.ForeignKey(
        Member,
        verbose_name=_('payee'),
        on_delete=models.CASCADE
    )

    def __str__(self):
        return '%s -> %s (%s)' % (
            self.from_place,
            self.to_place,
            self.payee
        )

    @property
    def amount(self):
        return self.kilometers * Decimal('0.3')

    class Meta:
        verbose_name = _('Traveling cost')
        verbose_name_plural = _('Traveling costs')
        ordering = ['date', 'payee', 'id']

src/stock/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.utils import timezone
from members.models import Member
from events.models import Event

# Create your models here.

STOCK_CATEGORIES = (
    (0, _('tents')),
    (1, _('kitchen')),
    (2, _('books')),
    (9, _('miscellaneous')),
)


class Order(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_('member'))
    item_no = models.CharField(_('item number'), max_length=10)
    name = models.CharField(_('name'), max_length=50)
    count = models.IntegerField(_('count'), default=1)
    size_color = models.CharField(_('size or color'), max_length=30, null=True, blank=True)
    prize = models.DecimalField(_('prize'), max_digits=5, decimal_places=2)
    date = models.DateField(_('date'), default=timezone.now)
    comment = models.TextField(_('comment'), null=True, blank=True)
    payed_by_group = models.BooleanField(_('payed by group'), default=False)
    completed = models.BooleanField(_('completed'), default=False)

    def __str__(self):
        return '%s (%s)' % (self.name, self.member)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')
        ordering = ['date', 'member', 'item_no']


class Item(models.Model):
    item_no = models.CharField(_('item number'), primary_key=True, max_length=10)
    name = models.CharField(_('name'), max_length=50)
    prize = models.DecimalField(_('prize'), max_digits=5, decimal_places=2)
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return '%s (#%s)' % (self.name, self.item_no)

    class Meta:
        verbose_name = _('Item')
        verbose_name_plural = _('Items')
        ordering = ['item_no']


class Stock(models.Model):
    name = models.CharField(_('name'), max_length=30)
    category = models.IntegerField(_('category'), choices=STOCK_CATEGORIES)
    place = models.CharField(_('place'), max_length=30)
    comments = models.TextField(_('comments'), null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Stock')
        verbose_name_plural = _('Stock')
        ordering = ['category', 'name']


class Reservation(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, verbose_name=_('stock'))
    from_time = models.DateTimeField(_('from'))
    to_time = models.DateTimeField(_('to'))
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_('member'))
    event = models.ForeignKey(Event, on_delete=models.CASCADE,
                              verbose_name=_('event'), null=True, blank=True)
    comments = models.TextField(_('comments'), null=True, blank=True)

    def __str__(self):
        return '%s :%s - %s' % (self.stock, self.from_time, self.to_time)

    class Meta:
        verbose_name = _('Reservation')
        verbose_name_plural = _('Reservations')
        ordering = ['stock', 'from_time', 'to_time']

src/finances/templates/finances/accounts.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap %}
{% load permission_tags %}

{% block content %}
	<div class="row">
		<div class="col">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Year" %}</h1>
					</div>
				</div>
				<div class="row px-2">
                                        {% for year in years %}
                                                <div class="col-auto px-0">
                                                        {% if current_year == year %}
                                                                <a class="btn btn-primary mx-2 px-3" href="{% url 'finances:accounts' year %}">{{ year }}</a>
                                                        {% else %}
                                                                <a class="btn btn-secondary mx-2 px-3" href="{% url 'finances:accounts' year %}">{{ year }}</a>
                                                        {% endif %}
                                                </div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 mt-4">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Asset accounts" %}</h1>
						{% for account in asset_accounts %}
                                <h2 class="text-center">{{ account.name }} {% if account.closed %}({% trans "closed" %}){% endif %}</h3>
                                <div class="row mx-auto my-auto justify-content-center">
                                        <div class="col-md-6 pr-0">
                                                <h3 class="text-center">{% trans "Debit" %}</h3>
                                                <table class="table table-borderless table-striped table-hover table-sm table-debit">
                                                        {% for type,entry in account.get_entries_with_type %}
                                                                {% if type == 'debit' %}
                                                                        <tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
                                                                                <td>{{ entry.id }}</td>
                                                                                <td>{{ entry.credit_account }}</td>
                                                                                <td>{{ entry.amount }}</td>
                                                                        </tr>
                                                                {% else %}
                                                                        <tr>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                        </tr>
                                                                {% endif %}
                                                        {% endfor %}
                                                </table>
                                        </div>
                                        <div class="col-md-6 pl-0">
                                                <h3 class="text-center">{% trans "Credit" %}</h3>
                                                <table class="table table-borderless table-striped table-hover table-sm table-credit">
                                                        {% for type,entry in account.get_entries_with_type %}
                                                                {% if type == 'credit' %}
                                                                        <tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
                                                                                <td>{{ entry.id }}</td>
                                                                                <td>{{ entry.debit_account }}</td>
                                                                                <td>{{ entry.amount }}</td>
                                                                        </tr>
                                                                {% else %}
                                                                        <tr>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                        </tr>
                                                                {% endif %}
                                                        {% endfor %}
                                                </table>
                                        </div>
										{% with type=account.get_balance_with_type.0 %}
											{% if type == 'debit' %}
													<h4 class="text-center">{% trans "Balance" %}: {{ account.get_balance_with_type.1 }} {% trans "Debit" %}</h3>
											{% else %}
													<h4 class="text-center">{% trans "Balance" %}: {{ account.get_balance_with_type.1 }} {% trans "Credit" %}</h3>
											{% endif %}
										{% endwith %}
                                </div>
                                {% if user|has_role:'board,cashier' %}
                                        <div class="row justify-content-center">
                                                <a class="btn btn-sm btn-primary mx-3" href="{% url 'finances:edit_account' account.id %}">{% trans "Edit" %}</a>
                                        </div>
                                {% endif %}
                                <hr>
                        {% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 mt-4">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Profit and loss accounts" %}</h1>
						{% for account in pal_accounts %}
                                <h2 class="text-center">{{ account.name }} {% if account.closed %}({% trans "closed" %}){% endif %}</h3>
                                <div class="row mx-auto my-auto justify-content-center">
                                        <div class="col-md-6 pr-0">
                                                <h3 class="text-center">{% trans "Debit" %}</h3>
                                                <table class="table table-borderless table-striped table-hover table-sm table-debit">
                                                        {% for type,entry in account.get_entries_with_type %}
                                                                {% if type == 'debit' %}
                                                                        <tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
                                                                                <td >{{ entry.id }}</td>
                                                                                <td>{{ entry.credit_account }}</td>
                                                                                <td>{{ entry.amount }}</td>
                                                                        </tr>
                                                                {% else %}
                                                                        <tr>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                        </tr>
                                                                {% endif %}
                                                        {% endfor %}
                                                </table>
                                        </div>
                                        <div class="col-md-6 pl-0">
                                                <h3 class="text-center">{% trans "Credit" %}</h3>
                                                <table class="table table-borderless table-striped table-hover table-sm table-credit">
                                                        {% for type,entry in account.get_entries_with_type %}
                                                                {% if type == 'credit' %}
                                                                        <tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
                                                                                <td>{{ entry.id }}</td>
                                                                                <td>{{ entry.debit_account }}</td>
                                                                                <td>{{ entry.amount }}</td>
                                                                        </tr>
                                                                {% else %}
                                                                        <tr>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                                <td>&nbsp;</td>
                                                                        </tr>
                                                                {% endif %}
                                                        {% endfor %}
                                                </table>
                                        </div>
										{% with type=account.get_balance_with_type.0 %}
											{% if type == 'debit' %}
													<h4 class="text-center">{% trans "Balance" %}: {{ account.get_balance_with_type.1 }} {% trans "Debit" %}</h3>
											{% else %}
													<h4 class="text-center">{% trans "Balance" %}: {{ account.get_balance_with_type.1 }} {% trans "Credit" %}</h3>
											{% endif %}
										{% endwith %}
                                </div>
                                {% if user|has_role:'board,cashier' %}
                                        <div class="row justify-content-center">
                                                <a class="btn btn-sm btn-primary mx-3" href="{% url 'finances:edit_account' account.id %}">{% trans "Edit" %}</a>
                                        </div>
                                {% endif %}
                                <hr>
                        {% endfor %}

					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row justify-content-center mt-4 mb-4 mb-sm-0">
                {% if user|has_role:'board,cashier' %}
                        <div class="col-auto my-3 text-center">
                                <a class="btn btn-lg btn-success mx-3" href="{% url 'finances:create_account' %}">{% trans "Create account" %}</a>
                        </div>
                        <div class="col-auto my-3 text-center">
                                <a class="btn btn-lg btn-danger mx-3" href="{% url 'finances:close_accounts' current_year %}">{% trans "Close accounts" %}</a>
                        </div>
                {% endif %}
                <div class="col-auto my-3 text-center">
                        <a class="btn btn-lg btn-primary mx-3" href="{% url 'finances:export_account' current_year %}">{% trans "Export accounts" %}</a>
		</div>
	</div>
{% endblock %}

src/finances/templates/finances/debit_confirm_export.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap %}
{% load render_table from django_tables2 %}

{% block content %}
	<div class="row">
		<div class="col mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Confirm debit export" %}</h1>
				<div class="row">
					<div class="col">
						<p>{% trans "The following debits will be exported and completed:" %}</p>
						<div class="table-responsive">
							<form action="{% url 'finances:export_debit' %}" method="post">
								{% csrf_token %}
								{% render_table table %}
								<button type="submit" id="id_download" class="btn btn-primary">{% trans "Confirm" %}</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		$(document).on("click", "#id_download", function () {
			setTimeout(function () {
				window.location = "{% url 'finances:debits' %}";
			}, 1000);
		});
	</script>
{% endblock %}

src/finances/templates/finances/old_debits.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Old debits" %}</h1>
						<h3 class="text-center">{{ group.execution_date|date }}</h3>
					</div>
				</div>
				{% if filter %}
					<div class="row mb-4 mt-3">
						<div class="col">
							<form action="" method="get" class="form form-inline justify-content-center">
								<div class="form-group">
									<div class="input-group">
										<input class="form-control" name="member_reference" maxlength="50" size="30" id="id_name" type="text" placeholder="{% trans "Member or reference" %}" value="{{ request.GET.member_reference }}">
										<div class="input-group-append">
											<button type="submit" class="btn btn-primary">{% trans "Search" %}</button>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				{% endif %}
				<div class="row">
					<div class="col">
						<div class="table-responsive">
							{% render_table table %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row justify-content-center mt-4 mb-4 mb-sm-0">
		<div class="col-auto my-3 text-center">
			<a class="btn btn-lg btn-primary mx-3" href="{% url 'finances:export_debits' group.id %}">{% trans "Export debits" %}</a>
		</div>
	</div>

	<script>
		$('#id_completed').change(function() {
			$(this).closest('form').submit();
		});
	</script>
{% endblock %}