src/authentication/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'auth'

urlpatterns = [
    path(_('login/'), views.SVLoginView.as_view(), name='login'),
    path(_('logout/'), views.SVLogoutView.as_view(), name='logout'),
    path(_('password-change/'), views.SVPasswordChangeView.as_view(), name='password-change'),
    path(_('password-reset/'), views.SVPasswordResetView.as_view(), name='password-reset'),
    path(_('password-reset-confirm/<uidb64>/<token>/'), views.SVPasswordResetConfirmView.as_view(),
         name='password-reset-confirm'),
    path(_('register/'), views.UserRegistrationView.as_view(), name='register'),
    path(_('register-confirm/<uidb64>/<token>/'), views.UserRegistrationConfirmView.as_view(),
         name='register-confirm'),
    path(_('administration/'), views.AdministrationView.as_view(), name='administration'),
    path(_('delete-rr/<pk>/'), views.RegistrationRequestDeleteView.as_view(), name='delete_rr'),
    path(_('confirm-rr/<pk>/'), views.RegistrationRequestConfirmView.as_view(), name='confirm_rr'),
    path(_('settings/'), views.SettingsListView.as_view(), name='settings'),
    path(
        _('create-bankdetails/'),
        views.BankDetailsCreateView.as_view(),
        name='create_bankdetails'
    ),
    path(
        _('edit-bankdetails/<pk>/'),
        views.BankDetailsUpdateView.as_view(),
        name='edit_bankdetails'
    ),
    path(
        _('delete-bankdetails/<pk>/'),
        views.BankDetailsDeleteView.as_view(),
        name='delete_bankdetails'
    ),
    path(
        _('edit-user/<pk>/'),
        views.SVUserUpdateView.as_view(),
        name='edit_user'
    ),
    path(
        _('delete-user/<pk>/'),
        views.SVUserDeleteView.as_view(),
        name='delete_user'
    ),
    path(_('legal-terms/'), views.LegalTermsView.as_view(), name='legal_terms'),
    path(_('privacy-policy/'), views.PrivacyPolicyView.as_view(), name='privacy_policy'),
]

src/stock/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'stock'

urlpatterns = [
    path(
        _('orders/'),
        views.OrderListView.as_view(),
        name='orders'
    ),
    path(
        _('create-order/'),
        views.OrderCreateView.as_view(),
        name='create_order'
    ),
    path(
        _('edit-order/<pk>/'),
        views.OrderUpdateView.as_view(),
        name='edit_order'
    ),
    path(
        _('delete-order/<pk>/'),
        views.OrderDeleteView.as_view(),
        name='delete_order'
    ),
    path(
        _('complete-order/<pk>/'),
        views.OrderCompleteView.as_view(),
        name='complete_order'
    ),
    path(
        _('stock/'),
        views.StockListView.as_view(),
        name='stock'
    ),
    path(
        _('create-stock/'),
        views.StockCreateView.as_view(),
        name='create_stock'
    ),
    path(
        _('edit-stock/<pk>/'),
        views.StockUpdateView.as_view(),
        name='edit_stock'
    ),
    path(
        _('delete-stock/<pk>/'),
        views.StockDeleteView.as_view(),
        name='delete_stock'
    ),
    path(
        _('reservations/<stock>/'),
        views.ReservationListView.as_view(),
        name='reservations'
    ),
    path(
        _('create-reservation/<stock>/'),
        views.ReservationCreateView.as_view(),
        name='create_reservation'
    ),
    path(
        _('edit-reservation/<pk>/'),
        views.ReservationUpdateView.as_view(),
        name='edit_reservation'
    ),
    path(
        _('delete-reservation/<pk>/'),
        views.ReservationDeleteView.as_view(),
        name='delete_reservation'
    ),
]

src/authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _

# Create your models here.

ROLES = (
        (0, _('Parent')),
        (1, _('Full-aged member')),
        (2, _('Leader')),
        (3, _('Board')),
        )


class SVUserManager(BaseUserManager):
    def _create_user(self, email, password, first_name, last_name, **other_fields):
        if not email:
            raise ValueError(_('The email adress has to be set!'))
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, password, first_name, last_name, **other_fields):
        other_fields.setdefault('is_active', False)
        other_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, first_name, last_name, **other_fields)

    def create_superuser(self, email, password, first_name, last_name, **other_fields):
        other_fields.setdefault('is_active', True)
        other_fields.setdefault('is_superuser', True)

        if other_fields.get('is_active') is not True:
            raise ValueError(_('Superuser must have is_active=True.'))
        if other_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self._create_user(email, password, first_name, last_name, **other_fields)


class SVUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), max_length=50, unique=True)
    first_name = models.CharField(_('first name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=50)
    is_active = models.BooleanField(_('active'), default=False)
    is_superuser = models.BooleanField(_('superuser'), default=False)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = SVUserManager()

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    @property
    def is_staff(self):
        return self.is_superuser

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


class RegistrationRequest(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    role = models.IntegerField(_('role'), choices=ROLES)
    members = models.CharField(_('members'), max_length=200)
    email_confirmed = models.BooleanField(_('email confirmed'), default=False)
    date = models.DateTimeField(_('date'), auto_now=True)

    def __str__(self):
        return '%s (%s)' % (self.user.get_full_name(), self.get_role_display())

    class Meta:
        verbose_name = _('registration request')
        verbose_name_plural = _('registration requests')
        ordering = ['date']


class BankDetails(models.Model):
    depositor = models.CharField(_('depositor'), max_length=50)
    iban = models.CharField('IBAN', max_length=34)
    bic = models.CharField('BIC', max_length=11)
    bank = models.CharField(_('bank'), max_length=30)
    user = models.ForeignKey(SVUser, on_delete=models.CASCADE, verbose_name=_('user'))

    def __str__(self):
        return '%s (%s)' % (self.depositor, self.iban)

    class Meta:
        verbose_name = _('Bank details')
        verbose_name_plural = _('Bank details')
        ordering = ['depositor', 'iban']


class MemberEmailSettings(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    event_created = models.BooleanField(
        _('A new event has been created'),
        default=True
    )
    member_created = models.BooleanField(
        _('A member has been assigned to your user'),
        default=True
    )
    member_changed = models.BooleanField(
        _('The data about one of your member has been changed'),
        default=False
    )
    mandate_changed = models.BooleanField(
        _('The data about one of your SEPA mandates has been changed'),
        default=False
    )
    debit_collected = models.BooleanField(
        _('Debits will be withdrawn'),
        default=True
    )
    order_completed = models.BooleanField(
        _('An order has been completed'),
        default=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = _('Member email settings')
        verbose_name_plural = _('Member email settings')
        ordering = ['user']


class LeaderEmailSettings(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    event_changed = models.BooleanField(
        _('A event has changed'),
        default=False
    )
    participation_changed = models.BooleanField(
        _('A member has enrolled or disenrolled for an event'),
        default=False
    )
    group_changed = models.BooleanField(
        _('A member of your group has changed or has been added/removed to/from it'),
        default=True
    )
    settlement_completed = models.BooleanField(
        _('A settlement of yours has been completed'),
        default=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = _('Leader email settings')
        verbose_name_plural = _('Leader email settings')
        ordering = ['user']


class CashierEmailSettings(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    debit_available = models.BooleanField(
        _('Debits for a month are available'),
        default=True
    )
    settlement_created = models.BooleanField(
        _('A settlement has been created'),
        default=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = _('Cashier email settings')
        verbose_name_plural = _('Cashier email settings')
        ordering = ['user']


class StockEmailSettings(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    order_created = models.BooleanField(
        _('An order has been created'),
        default=True
    )
    reservation_created = models.BooleanField(
        _('A reservation has been created'),
        default=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = _('Stock email settings')
        verbose_name_plural = _('Stock email settings')
        ordering = ['user']


class BoardEmailSettings(models.Model):
    user = models.OneToOneField(SVUser, verbose_name=_('user'), on_delete=models.CASCADE)
    rr_created = models.BooleanField(
        _('A user registration has been requested'),
        default=True
    )

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = _('Board email settings')
        verbose_name_plural = _('Board email settings')
        ordering = ['user']

src/authentication/templates/authentication/bankdetails_confirm_delete.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron text-center">
				<h1>{% trans "Delete bank details" %}</h1>
				<form method="post">
					{% csrf_token %}
					<p>
						{% blocktrans %}
							Are you sure you want to delete "{{ object }}"?
						{% endblocktrans %}
					</p>
					<a class="btn btn-primary mr-2" href="{{ view.get_success_url }}">{% trans "Cancel"%}</a>
					<input class="btn btn-danger" type="submit" value="{% trans "Delete" %}">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

src/authentication/templates/authentication/form.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">{{ title }}</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% bootstrap_form form %}
					{{ form.media }}
					<input class="btn btn-primary" type="submit" value="{% trans "Save" %}">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

src/authentication/templates/authentication/legal_terms.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}
{% load render_table from django_tables2 %}

{% block content %}
	<div class="row">
		<div class="col">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Legal terms" %}</h1>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						Diese Homepage wird von  der Deutschen Pfadfinderschaft Sankt Georg (DPSG) Stamm St. Vitus Hirschaid herausgegeben.
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h3>Angaben gemäß § 5 TMG:</h3>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Anschrift</h4>
						DPSG Stamm St.Vitus Hirschaid
						<br>
						Realschulstr. 5
						<br>
						96114 Hirschaid
						<br>
						<br>
						Vertretungsberechtigt ist der Vereinsvorstand:
						<br>
						Daniel Schraudner, Katrin Wiechmann, Philipp Wiechmann
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Kontakt</h4>
						E-Mail: kontakt at pfadfinder-hirschaid.de
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV</h4>
						Daniel Schraudner
						<br>
						Rinnigstr. 25a
						<br>
						96114 Hirschaid
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h3>Haftungsausschluss:</h3>
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Datenschutzhinweise</h4>
						Hier finden sie unsere ausführlichen Datenschutzerklärungen.
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Haftung für Inhalte</h4>
						Die Inhalte unserer Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Haftung für Links</h4>
						Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.
					</div>
				</div>
				<div class="row mt-3">
					<div class="col">
						<h4>Urheberrecht</h4>
						Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

src/authentication/templates/authentication/login.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}

{% block navbar %}
{% endblock %}


{% block content %}

	<div class="jumbotron jumbotron-login mx-auto my-sm-5">
		<a href="/">
			<img src="{% static 'img/logo.png' %}" class="img-fluid">
		</a>
		<h3 class="text-center mb-4"><p class="rh">{% trans "Stammesverwaltung" %}</p></h3>
		<form action="" method="post">
			{% csrf_token %}
			{% for error in form.non_field_errors %}
				<div class="alert alert-danger">
					{{ error }}
				</div>
			{% endfor %}
			<div class="form-group">
				{% for error in form.username.errors %}
					<div class="alert alert-danger">
						{{ error }}
					</div>
				{% endfor %}
				<input class="form-control" name="username" autofocus="" maxlength="254" id="id_username" type="email" placeholder="{% trans "Email address" %}" required autofocus>
			</div>
			<div class="form-group">
				{% for error in form.password.errors %}
					<div class="alert alert-danger">
						{{ error }}
					</div>
				{% endfor %}
				<input class="form-control" name="password" required id="id_password" type="password" placeholder="{% trans "Password" %}">
				<input type="hidden" name="next" value="{{ next }}" />
			</div>
			<div class="form-group row text-center align-items-center">
				<div class="col-sm my-2">
					<button class="btn btn-lg btn-primary px-4" type="submit">{% trans "Login" %}</button>
				</div>
				<div class="col-sm my-2">
					<a href="{% url "auth:register" %}">{% trans "Register" %}</a>
				</div>
				<div class="col-sm my-2">
					<a href="{% url "auth:password-reset" %}">{% trans "Reset password" %}</a>
				</div>
			</div>
		</form>
{% endblock %}

{% block footer %}
{% endblock %}

src/authentication/templates/authentication/password_change.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}

{% block navbar %}
{% endblock %}

{% block content %}

<div class="jumbotron jumbotron-login mx-auto my-sm-5">
	<a href="/">
		<img src="{% static 'img/logo.png' %}" class="img-fluid">
	</a>
	<h3 class="text-center mb-3 mt-2"><p class="rh">{% trans "Stammesverwaltung" %}</p></h3>
	<h5 class="text-center mb-4"><p class="rh">{% trans "Change password" %}</p></h5>
	<p class="text-center">
		{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}
	</p>
	<form action="" method="post">
		{% csrf_token %}
		{% for error in form.non_field_errors %}
			<div class="alert alert-danger">
				{{ error }}
			</div>
		{% endfor %}
		<div class="form-group">
			{% for error in form.old_password.errors %}
				<div class="alert alert-danger">
					{{ error }}
				</div>
			{% endfor %}
			<input class="form-control" name="old_password" autofocus="" maxlength="254" id="id_old_password" type="password" placeholder="{% trans "Old password" %}" required autofocus>
		</div>
		<div class="form-group">
			{% for error in form.new_password1.errors %}
				<div class="alert alert-danger">
					{{ error }}
				</div>
			{% endfor %}
			<input class="form-control" name="new_password1" autofocus="" maxlength="254" id="id_new_password1" type="password" placeholder="{% trans "New password" %}" required autofocus>
		</div>
		<div class="form-group">
			{% for error in form.new_password2.errors %}
				<div class="alert alert-danger">
					{{ error }}
				</div>
			{% endfor %}
			<input class="form-control" name="new_password2" autofocus="" maxlength="254" id="id_new_password2" type="password" placeholder="{% trans "Confirm new password" %}" required autofocus>
		</div>
		<div class="form-group text-center mt-4">
				<button class="btn btn-lg btn-primary px-4" type="submit">{% trans "Change" %}</button>
		</div>
	</form>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

src/authentication/templates/authentication/password_reset.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}

{% block navbar %}
{% endblock %}

{% block content %}

<div class="jumbotron jumbotron-login mx-auto my-sm-5">
	<a href="/">
		<img src="{% static 'img/logo.png' %}" class="img-fluid">
	</a>
	<h3 class="text-center mb-3 mt-2"><p class="rh">{% trans "Stammesverwaltung" %}</p></h3>
	<h5 class="text-center mb-4"><p class="rh">{% trans "Reset password" %}</p></h5>
	<p class="text-center">
		{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}
	</p>
	<form action="" method="post">
		{% csrf_token %}
		{% for error in form.non_field_errors %}
			<div class="alert alert-danger">
				{{ error }}
			</div>
		{% endfor %}
		<div class="form-group">
			{% for error in form.email.errors %}
				<div class="alert alert-danger">
					{{ error }}
				</div>
			{% endfor %}
			<input class="form-control" name="email" autofocus="" maxlength="50" id="id_email" type="" placeholder="{% trans "Email address" %}" required autofocus>
		</div>
		<div class="form-group text-center mt-4">
				<button class="btn btn-lg btn-primary px-4" type="submit">{% trans "Reset" %}</button>
		</div>
	</form>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

src/authentication/templates/authentication/password_reset_email.html
{% extends "_base_email.html" %}

{% load i18n %}
{% load static %}

{% block heading %}
    {% trans "Password reset" %}
{% endblock %}

{% block message %}
    {% trans "You're receiving this email because you requested a password reset for your user account." %}
{% endblock %}

{% block pressbutton %}
    {% trans "Click the following button to choose a new password." %}
{% endblock %}

{% block buttontext %}
  {% trans "Reset password" %}
{% endblock %}

{% block buttoncolor %}{% with buttoncolor="#0069d9" %}{{ block.super }}{% endwith %}{% endblock %}

{% block url %}{% url 'auth:password-reset-confirm' uidb64=uid token=token %}{% endblock %}

src/authentication/templates/authentication/register_email.html
{% extends "_base_email.html" %}

{% load i18n %}
{% load static %}

{% block heading %}
    {% trans "Confirm your email address" %}
{% endblock %}

{% block message %}
    {% trans "to finish your registration, please confirm your email address by clicking the confirmation button below." %}
{% endblock %}

{% block pressbutton %}
{% endblock %}

{% block buttontext %}
  {% trans "Confirm email address" %}
{% endblock %}

{% block buttoncolor %}{% with buttoncolor="#218838" %}{{ block.super }}{% endwith %}{% endblock %}

{% block url %}{% url 'auth:register-confirm' uidb64=uid token=token %}{% endblock %}

src/authentication/templates/authentication/rr_board_email.html
{% extends "_base_email.html" %}

{% load i18n %}
{% load static %}

{% block heading %}
{% trans "New registration request" %}
{% endblock %}

{% block message %}
{% blocktrans %}"{{ user }}" wants to register for the Stammesverwaltung. You need to confirm this request.{% endblocktrans %}
{% endblock %}

{% block pressbutton %}
{% trans "Click the following button to see all registration requests." %}
{% endblock %}

{% block buttontext %}
{% trans "Show registration requests" %}
{% endblock %}

{% block buttoncolor %}{% with buttoncolor="#0069d9" %}{{ block.super }}{% endwith %}{% endblock %}

{% block url %}{% url 'auth:administration' %}{% endblock %}

src/authentication/templates/authentication/settings.html
{% extends "_base.html" %}

{% load i18n %}
{% load static %}
{% load render_table from django_tables2 %}
{% load permission_tags %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "Settings" %}</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row mt-4">
		<div class="col">
			<div class="jumbotron col px-auto">
				<div class="row">
					<div class="col">
						<h1 class="text-center">{% trans "E-Mail settings" %}</h1>
						{% trans "Check when email should be sent:"%}
					</div>
				</div>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6">
							<div class="row mt-2">
								<div class="col">
									<h2>{% trans "Members" %}</h2>
								</div>
							</div>
							<div class="row mt-2">
								<div class="col">
									{{ member_email_form|bootstrap }}
								</div>
							</div>
						</div>
						{% if user|has_role:'board,leader' %}
							<div class="col-md-6">
								<div class="row mt-2">
									<div class="col">
										<h2>{% trans "Leader" %}</h2>
									</div>
								</div>
								<div class="row mt-2">
									<div class="col">
										{{ leader_email_form|bootstrap }}
									</div>
								</div>
							</div>
						{% endif %}
						{% if user|has_role:'board,cashier' %}
							<div class="col-md-6">
								<div class="row mt-2">
									<div class="col">
										<h2>{% trans "Cashier" %}</h2>
									</div>
								</div>
								<div class="row mt-2">
									<div class="col">
										{{ cashier_email_form|bootstrap }}
									</div>
								</div>
							</div>
						{% endif %}
						{% if user|has_role:'board,stock_warden' %}
							<div class="col-md-6">
								<div class="row mt-2">
									<div class="col">
										<h2>{% trans "Stock" %}</h2>
									</div>
								</div>
								<div class="row mt-2">
									<div class="col">
										{{ stock_email_form|bootstrap }}
									</div>
								</div>
							</div>
						{% endif %}
						{% if user|has_role:'board' %}
							<div class="col-md-6">
								<div class="row mt-2">
									<div class="col">
										<h2>{% trans "Board" %}</h2>
									</div>
								</div>
								<div class="row mt-2">
									<div class="col">
										{{ board_email_form|bootstrap }}
									</div>
								</div>
							</div>
						{% endif %}
					</div>
					<div class="row">
						<div class="col">
							<input class="btn btn-primary" type="submit" value="{% trans "Save" %}">
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	{% if user|has_role:'board,leader,cashier' %}
		<div class="row mt-4">
			<div class="col">
				<div class="jumbotron col px-auto">
					<div class="row">
						<div class="col">
							<h1 class="text-center">{% trans "Bank details" %}</h1>
						</div>
					</div>
					<div class="row">
						<div class="col">
							<div class="table-responsive">
									{% render_table tables.0 %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row justify-content-center mt-4 mb-4 mb-sm-0">
			<div class="col-auto my-3 text-center">
				<a class="btn btn-lg btn-success mx-3" href="{% url 'auth:create_bankdetails' %}">{% trans "Create bank details" %}</a>
			</div>
		</div>
	{% endif %}
{% endblock %}