src/events/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'events'

urlpatterns = [
    path(
        _('subvention-list/<event>/'),
        views.SubventionListView.as_view(),
        name='subvention_list'
    ),
    path(
        _('participant-list/<event>/'),
        views.ParticipantListView.as_view(),
        name='participant_list'
    ),
    path(_('create-event/'), views.EventCreateWizardView.as_view(), name='create_event'),
    path(_('edit-event/<pk>/'), views.EventUpdateView.as_view(), name='edit_event'),
    path(_('delete-event/<pk>/'), views.EventDeleteView.as_view(), name='delete_event'),
    path(
        _('create-participation/<event>/'),
        views.ParticipationCreateView.as_view(),
        name='create_participation'
    ),
    path(
        _('edit-participation/<pk>/'),
        views.ParticipationUpdateView.as_view(),
        name='edit_participation'
    ),
    path(
        _('delete-participation/<pk>/'),
        views.ParticipationDeleteView.as_view(),
        name='delete_participation'
    ),
    path(_('letter-preview/'), views.LetterPreviewView.as_view(), name='letter_preview'),
    path('<pk>/', views.EventDetailView.as_view(), name='details'),
    path('', views.EventListView.as_view(), name='list'),
]

src/stock/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'stock'

urlpatterns = [
    path(
        _('orders/'),
        views.OrderListView.as_view(),
        name='orders'
    ),
    path(
        _('create-order/'),
        views.OrderCreateView.as_view(),
        name='create_order'
    ),
    path(
        _('edit-order/<pk>/'),
        views.OrderUpdateView.as_view(),
        name='edit_order'
    ),
    path(
        _('delete-order/<pk>/'),
        views.OrderDeleteView.as_view(),
        name='delete_order'
    ),
    path(
        _('complete-order/<pk>/'),
        views.OrderCompleteView.as_view(),
        name='complete_order'
    ),
    path(
        _('stock/'),
        views.StockListView.as_view(),
        name='stock'
    ),
    path(
        _('create-stock/'),
        views.StockCreateView.as_view(),
        name='create_stock'
    ),
    path(
        _('edit-stock/<pk>/'),
        views.StockUpdateView.as_view(),
        name='edit_stock'
    ),
    path(
        _('delete-stock/<pk>/'),
        views.StockDeleteView.as_view(),
        name='delete_stock'
    ),
    path(
        _('reservations/<stock>/'),
        views.ReservationListView.as_view(),
        name='reservations'
    ),
    path(
        _('create-reservation/<stock>/'),
        views.ReservationCreateView.as_view(),
        name='create_reservation'
    ),
    path(
        _('edit-reservation/<pk>/'),
        views.ReservationUpdateView.as_view(),
        name='edit_reservation'
    ),
    path(
        _('delete-reservation/<pk>/'),
        views.ReservationDeleteView.as_view(),
        name='delete_reservation'
    ),
]

src/events/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from members.models import Section, Member

# Create your models here.

LEVEL = (
        (0, _('Group')),
        (1, _('District')),
        (2, _('Diocese')),
        (3, _('Association')),
        (4, 'WOSM'),
        )

TYPES = (
        (0, _('Text')),
        (1, _('Textarea')),
        (2, _('Number')),
        (3, _('Choice')),
        (4, _('Radiobutton')),
        )


class Event(models.Model):
    name = models.CharField(_('name'), max_length=50)
    from_date = models.DateField(_('from'))
    to_date = models.DateField(_('to'))
    place = models.CharField(_('place'), max_length=50, null=True, blank=True)
    fee = models.DecimalField(_('fee'), max_digits=5, decimal_places=2)
    sections = models.ManyToManyField(Section, verbose_name=_('sections'))
    level = models.IntegerField(_('level'), choices=LEVEL)
    description = models.TextField(_('description'), null=True, blank=True)
    deadline = models.DateField(_('deadline'))
    letter = models.FileField(_('letter'), null=True, blank=True)
    participants = models.ManyToManyField(
            Member,
            through='Participation',
            verbose_name=_('participants')
    )
    scoutnet_id = models.IntegerField('Scoutnet ID', null=True, blank=True)
    account = models.ForeignKey(
        'finances.Account',
        verbose_name=_('account'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = ['-from_date']


class Participation(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_('member'))
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name=_('event'))
    time = models.DateTimeField(_('time of enrollment'), auto_now=True)

    def __str__(self):
        return "%s -> %s" % (self.member, self.event)

    class Meta:
        verbose_name = _('participation')
        verbose_name_plural = _('participations')
        unique_together = ('member', 'event')


class EventField(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name=_('event'))
    type = models.IntegerField(_('type'), choices=TYPES)
    name = models.CharField(_('name'), max_length=100)
    required = models.BooleanField(_('required'), default=False)
    choices = models.CharField(_('choices'), max_length=200, blank=True, null=True)

    def __str__(self):
        return "%s: %s" % (self.name, self.get_type_display())

    class Meta:
        verbose_name = _('Event field')
        verbose_name_plural = _('Event fields')


class ParticipationField(models.Model):
    event_field = models.ForeignKey(
        EventField,
        on_delete=models.CASCADE,
        verbose_name=_('event field')
    )
    participation = models.ForeignKey(
        Participation,
        on_delete=models.CASCADE,
        verbose_name=_('participation')
    )
    value = models.CharField(_('value'), max_length=100)

    def __str__(self):
        return "%s (%s)" % (self.value, self.event_field)

    class Meta:
        verbose_name = _('Participation field')
        verbose_name_plural = _('Participation fields')

src/events/forms.py
from django import forms
from django.core.exceptions import ValidationError
from members.models import Member
from django.utils.translation import gettext_lazy as _
from django.forms import inlineformset_factory
from bootstrap_datepicker_plus.widgets import DatePickerInput

from members.models import Section
from . import models
from config.widgets import EURWidget, FileWidget
from config.widgets import BootstrapSelect2Widget, BootstrapSelect2MultipleWidget

TYPE_MAP = {
            0: forms.CharField(max_length=100),
            1: forms.CharField(
                max_length=100,
                widget=forms.Textarea(attrs={'rows': 5, 'cols': 30})
            ),
            2: forms.IntegerField(),
            3: forms.ChoiceField(),
            4: forms.ChoiceField(widget=forms.RadioSelect)
}

BOOL_CHOICES = ((True, _('Yes')), (False, _('No')))


class ParticipationCreateForm(forms.ModelForm):
    """
    Form for the creation of Participations in ParticipationCreateView.

    The users can choose from all their members which are not enrolled yet.
    All the EventField for the event are taken to build the form dynamically.
    For the value of every EventField a ParticipationField is stored related to the participation.
    """

    def __init__(self, user=None, event=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.fields['member'].queryset = Member.objects.filter(
            user=user
        ).exclude(
            participation__event=event
        )
        self.event_fields = models.EventField.objects.filter(event=event)
        for field in self.event_fields:
            self.fields[field.name] = TYPE_MAP[field.type]
            self.fields[field.name].required = field.required
            self.fields[field.name].label = field.name
            if field.choices:
                choices = field.choices.split(',')
                self.fields[field.name].choices = list(zip(choices, choices))

    def clean_member(self):
        member = self.cleaned_data['member']
        if member.user != self.user:
            raise ValidationError(_('Invalid member'), code='invalid')
        return member

    def save(self, commit=True):
        p = super().save()
        for field in self.event_fields:
            models.ParticipationField.objects.create(
                event_field=field,
                participation=p,
                value=self.cleaned_data[field.name]
            )
        return p

    class Meta:
        model = models.Participation
        fields = ['member']
        widgets = {
            'member': BootstrapSelect2Widget,
        }


class ParticipationUpdateForm(forms.ModelForm):
    def __init__(self, event=None, instance=None, *args, **kwargs):
        super().__init__(instance=instance, *args, **kwargs)
        self.event_fields = models.EventField.objects.filter(event=event)
        for field in self.event_fields:
            self.fields[field.name] = TYPE_MAP[field.type]
            self.fields[field.name].required = field.required
            if field.choices:
                choices = field.choices.split(',')
                self.fields[field.name].choices = list(zip(choices, choices))
            if instance:
                try:
                    self.fields[field.name].initial = models.ParticipationField.objects.get(
                        participation=instance,
                        event_field=field
                    ).value
                except Exception:
                    pass

    def save(self, commit=True):
        p = super().save()
        for field in self.event_fields:
            models.ParticipationField.objects.update_or_create(
                event_field=field,
                participation=p,
                defaults={'value': self.cleaned_data[field.name]}
            )
        return p

    class Meta:
        model = models.Participation
        fields = []


class EventUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = [
            'name',
            'from_date',
            'to_date',
            'place',
            'fee',
            'sections',
            'level',
            'description',
            'deadline',
            'letter',
            'scoutnet_id',
        ]
        widgets = {
            'from_date': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'to_date': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'fee': EURWidget,
            'sections': BootstrapSelect2MultipleWidget,
            'level': BootstrapSelect2Widget,
            'deadline': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'letter': FileWidget,
            'scoutnet_id': forms.NumberInput(attrs={'min': '0'})
        }


class EventGeneralForm(forms.ModelForm):
    def import_scoutnet(self, event):
        self.fields['name'].initial = event['title']
        self.fields['from_date'].initial = event['start_date']
        self.fields['to_date'].initial = event['end_date']
        self.fields['place'].initial = event['location']
        sections = Section.objects.exclude(name='Ehemalige')

        if 'Wölfling' not in event['stufen']:
            sections = sections.exclude(name='Wölfling')
        if 'Jungpfadfinder' not in event['stufen']:
            sections = sections.exclude(name='Jungpfadfinder')
        if 'Pfadfinder' not in event['stufen']:
            sections = sections.exclude(name='Pfadfinder')
        if 'Rover' not in event['stufen']:
            sections = sections.exclude(name='Rover')
        self.fields['sections'].initial = sections
        if event['ebene'] == 'St. Vitus Hirschaid':
            self.fields['level'].initial = 0
        elif event['ebene'] == 'Bezirk 2':
            self.fields['level'].initial = 1
        elif event['ebene'] == 'DV Bamberg':
            self.fields['level'].initial = 2
        self.fields['description'].initial = event['description']
        self.fields['scoutnet_id'].initial = event['id']

    class Meta:
        model = models.Event
        fields = [
            'name',
            'from_date',
            'to_date',
            'place',
            'sections',
            'level',
            'description',
            'scoutnet_id',
        ]
        widgets = {
            'from_date': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'to_date': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'sections': BootstrapSelect2MultipleWidget,
            'level': BootstrapSelect2Widget,
            'scoutnet_id': forms.NumberInput(attrs={'min': '0'})
        }


class EventLetterForm(forms.ModelForm):
    CHOICES = [
        ('True', 'Upload'),
        ('False', 'Create'),
    ]
    letter_source = forms.BooleanField(
            widget=forms.RadioSelect(choices=CHOICES),
            initial=True,
            required=False
    )

    class Meta:
        model = models.Event
        fields = [
            'fee',
            'deadline',
            'letter_source',
            'letter',
        ]
        widgets = {
            'fee': EURWidget,
            'deadline': DatePickerInput(options={'format': 'DD.MM.YYYY', 'locale': 'de'}),
            'letter': FileWidget,
        }


class EventFieldForm(forms.ModelForm):
    class Meta:
        model = models.EventField
        exclude = ['event']
        widgets = {
            'required': forms.RadioSelect(choices=[
                (False, _('No')),
                (True, _('Yes'))
            ]),
            'type': BootstrapSelect2Widget,
        }


EventFieldFormSet = inlineformset_factory(
    models.Event,
    models.EventField,
    form=EventFieldForm,
    extra=1
)


class LetterForm(forms.Form):
    title = forms.CharField(label=_('Title'), max_length=50)
    opening = forms.CharField(
        label=_('Opening'),
        max_length=100,
        initial=_('Dear scouts, dear parents,')
    )
    text = forms.CharField(label=_('Text'), widget=forms.Textarea)
    closing = forms.CharField(
        label=_('Closing'),
        max_length=50,
        initial=_('Be prepared, your Leaders'),
        disabled=True
    )
    summary = forms.BooleanField(label=_('Summary'), required=False)


class EventFinancesForm(forms.Form):
    create_account = forms.BooleanField(
        label=_('Create account for event?'),
        widget=forms.RadioSelect(
            choices=BOOL_CHOICES,
        ),
        initial=True,
        required=False
    )


class EventStockForm(forms.Form):
    pass


class EventConfirmationForm(forms.Form):
    pass

src/events/templates/events/event_confirm_delete.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron text-center">
				<h1>{% trans "Delete event" %}</h1>
				<form method="post">
					{% csrf_token %}
					<p>
						{% blocktrans %}
							Are you sure you want to delete "{{ object }}"?
						{% endblocktrans %}
					</p>
					<a class="btn btn-primary mr-2" href="{% url "events:details" object.id %}">{% trans "Cancel"%}</a>
					<input class="btn btn-danger" type="submit" value="{% trans "Delete" %}">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

src/events/templates/events/event_detail.html
{% extends "_base.html" %}

{% load i18n %}
{% load permission_tags %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mb-4">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Local" %}</h1>
				<table class="table table-borderless table-sm">
					<tr>
						<th>
							{% trans "Name" %}:
						</th>
						<td>{{ object.name }}</td>
					</tr>
					<tr>
						<th>
							{% trans "From" %}:
						</th>
						<td>{{ object.from_date|date }}</td>
					</tr>
					<tr>
						<th>
							{% trans "To" %}:
						</th>
						<td>{{ object.to_date|date }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Place" %}:
						</th>
						<td>{{ object.place|default:"" }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Sections" %}:
						</th>
						<td>{{ object.sections.all|join:", " }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Level" %}:
						</th>
						<td>{{ object.get_level_display }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Description" %}:
						</th>
						<td>{{ object.description }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Fee" %}:
						</th>
						<td>{{ object.fee }} EUR</td>
					</tr>
					<tr>
						<th>
							{% trans "Deadline" %}:
						</th>
						<td>{{ object.deadline|date }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Scoutnet ID" %}:
						</th>
						<td>{{ object.scoutnet_id|default:"" }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Letter" %}:
						</th>
						{% if object.letter %}
							<td><a href="{{ object.letter.url }}" target="_blank">{{ object.letter.name }}</a></td>
						{% else %}
							<td>--</td>
						{% endif %}
					</tr>
				</table>
				<div class="text-center">
					<a class="btn btn-primary mx-3 my-2 px-4" href="{% url "events:edit_event" object.id %}">{% trans "Edit" %}</a>
					<a class="btn btn-danger mx-3 my-2 px-4" href="{% url "events:delete_event" object.id %}">{% trans "Delete" %}</a>
				</div>
			</div>
		</div>
		<div class="col-md-6 mb-4">
			<div class="jumbotron">
				<h1 class="text-center">Scoutnet</h1>
				<table class="table table-borderless table-sm">
					<tr>
						<th>
							{% trans "Name" %}:
						</th>
						<td>{{ scoutnet_object.title }}</td>
					</tr>
					<tr>
						<th>
							{% trans "From" %}:
						</th>
						<td>{{ scoutnet_object.start_date|date }}</td>
					</tr>
					<tr>
						<th>
							{% trans "To" %}:
						</th>
						<td>{{ scoutnet_object.end_date|date }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Place" %}:
						</th>
						<td>{{ scoutnet_object.location }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Sections" %}:
						</th>
						<td>{{ scoutnet_object.stufen }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Level" %}:
						</th>
						<td>{{ scoutnet_object.ebene }}</td>
					</tr>
					<tr>
						<th>
							{% trans "Description" %}:
						</th>
						<td>{{ scoutnet_object.description }}</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 mb-4">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Participants" %}</h1>
				<div class="table-responsive">
					<table class="table table-striped table-hover">
						<tr>
							<th>{% trans "First name" %}</th>
							<th>{% trans "Last name" %}</th>
							<th>{% trans "Section" %}</th>
							<th>{% trans "Function" %}</th>
							<th>{% trans "Time of enrollment" %}</th>
							{% for ef in object.eventfield_set.all %}
								<th>{{ ef.name }}</th>
							{% endfor %}
						</tr>
						{% for p in participations %}
							<tr>
								<td>{{ p.member.first_name }}</td>
								<td>{{ p.member.last_name }}</td>
								<td>{{ p.member.section.name }}</td>
								<td>{{ p.member.get_function_display }}</td>
								<td>{{ p.time }}</td>
								{% for pf in p.participationfield_set.all %}
									<td>{{ pf.value }}</td>
								{% endfor %}
							</tr>
						{% endfor %}
					</table>
				</div>
				<div class="text-center">
					<a class="btn btn-primary mx-3 my-2 px-4" href="{% url "events:subvention_list" object.id %}">{% trans "Subvention list" %}</a>
					<a class="btn btn-primary mx-3 my-2 px-4" href="{% url "events:participant_list" object.id %}">{% trans "Participant list" %}</a>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 mb-4">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Debits" %}</h1>
				<table class="table table-striped table-hover">
					<tr>
						<th>{% trans "Date" %}</th>
						<th>{% trans "Count" %}</th>
						<th>{% trans "Sum" %}</th>
					</tr>
					{% for g in groups %}
						<tr>
							<td>{{ g.date }}</td>
							<td>{{ g.count }}</td>
							<td>{{ g.sum }} EUR</td>
						</tr>
					{% endfor %}
					<tr>
						<td>{{ current_group.date }} {% trans "(still open)" %}</td>
						<td>{{ current_group.count }}</td>
						<td>{{ current_group.sum }} EUR</td>
					</tr>
					<tr>
						<td>{% trans "Not yet created" %}</td>
						<td>{{ notcreated.count }}</td>
						<td>{{ notcreated.sum }} EUR</td>
					</tr>
					<tr>
						<th>{% trans "All" %}</th>
						<th>{{ all.count }}</th>
						<th>{{ all.sum }} EUR</th>
					</tr>
				</table>
				{% if user|has_role:'board' %}
					<div class="text-center">
						<a class="btn btn-success mx-3" href="{% url 'finances:create_event_debits' object.id %}">{% trans "Create missing debits" %}</a>
					</div>
				{% endif %}
			</div>
		</div>
		<div class="col-md-6 mb-4">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Account" %}</h1>
				{% if object.account %}
					<div class="row mx-auto my-auto justify-content-center">
						<div class="col-md-6 pr-0">
								<h3 class="text-center">{% trans "Debit" %}</h3>
								<table class="table table-borderless table-striped table-hover table-sm table-debit">
										{% for type,entry in object.account.get_entries_with_type %}
												{% if type == 'debit' %}
														<tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
																<td >{{ entry.id }}</td>
																<td>{{ entry.credit_account }}</td>
																<td>{{ entry.amount }}</td>
														</tr>
												{% else %}
														<tr>
																<td>&nbsp;</td>
																<td>&nbsp;</td>
																<td>&nbsp;</td>
														</tr>
												{% endif %}
										{% endfor %}
								</table>
						</div>
						<div class="col-md-6 pl-0">
								<h3 class="text-center">{% trans "Credit" %}</h3>
								<table class="table table-borderless table-striped table-hover table-sm table-credit">
										{% for type,entry in object.account.get_entries_with_type %}
												{% if type == 'credit' %}
														<tr data-tooltip="true" data-placement="bottom" title="{{ entry.date }}, {{ entry.comment }}">
																<td>{{ entry.id }}</td>
																<td>{{ entry.debit_account }}</td>
																<td>{{ entry.amount }}</td>
														</tr>
												{% else %}
														<tr>
																<td>&nbsp;</td>
																<td>&nbsp;</td>
																<td>&nbsp;</td>
														</tr>
												{% endif %}
										{% endfor %}
								</table>
						</div>
						{% with type=object.account.get_balance_with_type.0 %}
							{% if type == 'debit' %}
									<h4 class="text-center">{% trans "Balance" %}: {{ object.account.get_balance_with_type.1 }} {% trans "Debit" %}</h3>
							{% else %}
									<h4 class="text-center">{% trans "Balance" %}: {{ object.account.get_balance_with_type.1 }} {% trans "Credit" %}</h3>
							{% endif %}
						{% endwith %}
					</div>
					<div class="row mt-2">
						<div class="col text-center">
							<a class="btn btn-primary mx-3" href="{% url 'finances:event_export_voucher' object.id %}">{% trans "Vouchers" %}</a>
						</div>
					</div>
				{% else %}
					<div class="row mt-2">
						<div class="col text-center">
							<form action="{% url 'finances:create_event_account' object.id %}" method="post">
								{% csrf_token %}
								<input class="btn btn-success mx-3" type="submit" value="{% trans "Create" %}">
							</form>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Stock" %}</h1>
			</div>
		</div>
	</div>
{% endblock %}

src/events/templates/events/event_form.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">{{ title }}</h1>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% bootstrap_form form %}
					{{ form.media }}
					<input class="btn btn-primary" type="submit" value="{% trans "Save" %}">
				</form>
			</div>
		</div>
	</div>
{% endblock %}

src/events/templates/events/event_letter.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Create event" %}</h1>
				<h2 class="text-center">{% trans "Letter" %} {% with step=wizard.steps.step1 %}{% blocktrans with count=wizard.steps.count %}(Step {{ step }} of {{ count }}){% endblocktrans %}{% endwith %}</h2>
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{{ wizard.management_form }}
					{% bootstrap_form wizard.form %}
					{{ wizard.form.media }}
					<button class="btn btn-secondary mr-1" name="wizard_goto_step" value="{{ wizard.steps.prev }}">{% trans "Back" %}</button>
					<input class="btn btn-primary" type="submit" value="{% trans "Next" %}">
			</div>
		</div>
		<div class="col-md-6 mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">{% trans "Create letter" %}</h1>
					{% bootstrap_form letter_form %}
					<input class="btn btn-primary" formaction="{% url "events:letter_preview" %}" type="submit" disabled id="id_preview" formtarget="_blank" value="{% trans "Preview" %}">
				</form>
			</div>
		</div>
	</div>
	<script>
		$().ready(function() {
				$("#id_title").prop("disabled", true);	
				$("#id_opening").prop("disabled", true);	
				$("#id_text").prop("disabled", true);	
				$("#id_closing").prop("disabled", true);	
				$("#id_summary").prop("disabled", true);	
				$("#id_preview").prop("disabled", true);	
				$("#id_letter-letter_source_0").prop("checked", true);	
				$("#id_letter-letter_source_1").prop("checked", false);	
		});
		$('input[name=letter-letter_source]').change(function() {
			if(document.getElementById('id_letter-letter_source_0').checked) {
				$("#id_title").prop("disabled", true);	
				$("#id_opening").prop("disabled", true);	
				$("#id_text").prop("disabled", true);	
				$("#id_closing").prop("disabled", true);	
				$("#id_summary").prop("disabled", true);	
				$("#id_preview").prop("disabled", true);	

				$("#id_letter-letter").prop("disabled", false);	
			} else {
				$("#id_title").prop("disabled", false);	
				$("#id_opening").prop("disabled", false);	
				$("#id_text").prop("disabled", false);	
				$("#id_closing").prop("disabled", false);	
				$("#id_summary").prop("disabled", false);	
				$("#id_preview").prop("disabled", false);	

				$("#id_letter-letter").prop("disabled", true);	
			}
		});
	</script>
{% endblock %}

src/events/templates/events/participation_confirm_delete.html
{% extends "_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block content %}
	<div class="row">
		<div class="col-md-6 mx-auto">
			<div class="jumbotron text-center">
				<h1>{{ title }}</h1>
				<form method="post">
					{% csrf_token %}
					<p>
						{% with event=object.event %}
							{% blocktrans with member=object.member %}
								Are you sure you want to withdraw the enrollment of {{ member }} for {{ event }}?
							{% endblocktrans %}
						{% endwith %}
					</p>
					<a class="btn btn-primary mr-2" href="{% url "events:list" %}">{% trans "Cancel"%}</a>
					<input class="btn btn-danger" type="submit" value="{% trans "Withdraw" %}">
				</form>
			</div>
		</div>
	</div>
{% endblock %}